[package]
name = "tiger-car-ros"
version = "0.1.0"
authors = ["Dylan Staatz <dylanstaatz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11"
